// Auto-generated by collect-real-data.py on 2026-03-20
const REAL_DATA = {
  "projects": [
    {
      "name": "mutter",
      "category": "desktop",
      "platform": "gnome",
      "stars": 0,
      "swedishProgress": 99,
      "quality": 9,
      "lastUpdate": "2026-03-20T20:42:20Z",
      "totalStrings": 734,
      "translatedStrings": 726,
      "url": "https://l10n.gnome.org/module/mutter/",
      "langCode": "sv"
    },
    {
      "name": "w3m",
      "category": "desktop",
      "platform": "github",
      "stars": 0,
      "swedishProgress": 99,
      "quality": 7,
      "lastUpdate": "2026-03-20T20:42:23Z",
      "totalStrings": 674,
      "translatedStrings": 667,
      "url": "https://github.com/tats/w3m",
      "langCode": "sv"
    },
    {
      "name": "LocalizedMenu",
      "category": "desktop",
      "platform": "github",
      "stars": 0,
      "swedishProgress": 99,
      "quality": 7,
      "lastUpdate": "2026-03-20T20:42:28Z",
      "totalStrings": 799,
      "translatedStrings": 791,
      "url": "https://github.com/zam1024t/LocalizedMenu",
      "langCode": "sv"
    },
    {
      "name": "CRM",
      "category": "desktop",
      "platform": "github",
      "stars": 0,
      "swedishProgress": 99,
      "quality": 7,
      "lastUpdate": "2026-03-20T20:42:28Z",
      "totalStrings": 924,
      "translatedStrings": 914,
      "url": "https://github.com/eric-erki/CRM",
      "langCode": "sv"
    },
    {
      "name": "Firefox",
      "category": "web",
      "platform": "pontoon",
      "stars": 25000,
      "swedishProgress": 98,
      "quality": 9,
      "lastUpdate": "2026-03-20T20:42:20Z",
      "totalStrings": 15000,
      "translatedStrings": 14700,
      "url": "https://github.com/search?q=Firefox language:Swedish",
      "langCode": "sv"
    },
    {
      "name": "amarok",
      "category": "desktop",
      "platform": "kde",
      "stars": 0,
      "swedishProgress": 98,
      "quality": 8,
      "lastUpdate": "2026-03-20T20:42:20Z",
      "totalStrings": 1538,
      "translatedStrings": 1507,
      "url": "https://l10n.kde.org/stats/gui/trunk-kf6/amarok/sv/",
      "langCode": "sv"
    },
    {
      "name": "typograf",
      "category": "web",
      "platform": "github",
      "stars": 0,
      "swedishProgress": 98,
      "quality": 7,
      "lastUpdate": "2026-03-20T20:42:25Z",
      "totalStrings": 673,
      "translatedStrings": 659,
      "url": "https://github.com/typograf/typograf",
      "langCode": "sv"
    },
    {
      "name": "churchCRM",
      "category": "desktop",
      "platform": "github",
      "stars": 0,
      "swedishProgress": 98,
      "quality": 7,
      "lastUpdate": "2026-03-20T20:42:28Z",
      "totalStrings": 473,
      "translatedStrings": 463,
      "url": "https://github.com/moturiphil/churchCRM",
      "langCode": "sv"
    },
    {
      "name": "MangoIglesia",
      "category": "desktop",
      "platform": "github",
      "stars": 0,
      "swedishProgress": 98,
      "quality": 7,
      "lastUpdate": "2026-03-20T20:42:28Z",
      "totalStrings": 473,
      "translatedStrings": 463,
      "url": "https://github.com/memitoguate/MangoIglesia",
      "langCode": "sv"
    },
    {
      "name": "Discord-Codenames",
      "category": "development",
      "platform": "github",
      "stars": 0,
      "swedishProgress": 98,
      "quality": 7,
      "lastUpdate": "2026-03-20T20:42:28Z",
      "totalStrings": 648,
      "translatedStrings": 635,
      "url": "https://github.com/Mantouisyummy/Discord-Codenames",
      "langCode": "sv"
    },
    {
      "name": "SemanticMediaWiki",
      "category": "media",
      "platform": "github",
      "stars": 0,
      "swedishProgress": 98,
      "quality": 7,
      "lastUpdate": "2026-03-20T20:42:30Z",
      "totalStrings": 773,
      "translatedStrings": 757,
      "url": "https://github.com/SemanticMediaWiki/SemanticMediaWiki",
      "langCode": "sv"
    },
    {
      "name": "Krita",
      "category": "media",
      "platform": "kde",
      "stars": 6000,
      "swedishProgress": 97,
      "quality": 9,
      "lastUpdate": "2026-03-20T20:42:20Z",
      "totalStrings": 4000,
      "translatedStrings": 3880,
      "url": "https://github.com/search?q=Krita language:Swedish",
      "langCode": "sv"
    },
    {
      "name": "KDE Plasma",
      "category": "system",
      "platform": "kde",
      "stars": 2000,
      "swedishProgress": 97,
      "quality": 9,
      "lastUpdate": "2026-03-20T20:42:20Z",
      "totalStrings": 5000,
      "translatedStrings": 4850,
      "url": "https://github.com/search?q=KDE Plasma language:Swedish",
      "langCode": "sv"
    },
    {
      "name": "evince",
      "category": "desktop",
      "platform": "gnome",
      "stars": 0,
      "swedishProgress": 97,
      "quality": 9,
      "lastUpdate": "2026-03-20T20:42:20Z",
      "totalStrings": 702,
      "translatedStrings": 680,
      "url": "https://l10n.gnome.org/module/evince/",
      "langCode": "sv"
    },
    {
      "name": "glib",
      "category": "desktop",
      "platform": "gnome",
      "stars": 0,
      "swedishProgress": 97,
      "quality": 9,
      "lastUpdate": "2026-03-20T20:42:20Z",
      "totalStrings": 1397,
      "translatedStrings": 1355,
      "url": "https://l10n.gnome.org/module/glib/",
      "langCode": "sv"
    },
    {
      "name": "dolphin",
      "category": "desktop",
      "platform": "kde",
      "stars": 0,
      "swedishProgress": 97,
      "quality": 8,
      "lastUpdate": "2026-03-20T20:42:20Z",
      "totalStrings": 417,
      "translatedStrings": 404,
      "url": "https://l10n.kde.org/stats/gui/trunk-kf6/dolphin/sv/",
      "langCode": "sv"
    },
    {
      "name": "gnome-music",
      "category": "desktop",
      "platform": "gnome",
      "stars": 0,
      "swedishProgress": 96,
      "quality": 9,
      "lastUpdate": "2026-03-20T20:42:20Z",
      "totalStrings": 1226,
      "translatedStrings": 1176,
      "url": "https://l10n.gnome.org/module/gnome-music/",
      "langCode": "sv"
    },
    {
      "name": "CommunityCRM",
      "category": "games",
      "platform": "github",
      "stars": 0,
      "swedishProgress": 96,
      "quality": 7,
      "lastUpdate": "2026-03-20T20:42:28Z",
      "totalStrings": 321,
      "translatedStrings": 308,
      "url": "https://github.com/mukul4u2005/CommunityCRM",
      "langCode": "sv"
    },
    {
      "name": "Chromium",
      "category": "web",
      "platform": "github",
      "stars": 100000,
      "swedishProgress": 95,
      "quality": 9,
      "lastUpdate": "2026-03-20T20:42:20Z",
      "totalStrings": 25000,
      "translatedStrings": 23750,
      "url": "https://github.com/search?q=Chromium language:Swedish",
      "langCode": "sv"
    },
    {
      "name": "Signal Android",
      "category": "mobile",
      "platform": "transifex",
      "stars": 25000,
      "swedishProgress": 95,
      "quality": 9,
      "lastUpdate": "2026-03-20T20:42:20Z",
      "totalStrings": 2000,
      "translatedStrings": 1900,
      "url": "https://github.com/search?q=Signal Android language:Swedish",
      "langCode": "sv"
    },
    {
      "name": "WordPress",
      "category": "web",
      "platform": "github",
      "stars": 18000,
      "swedishProgress": 95,
      "quality": 9,
      "lastUpdate": "2026-03-20T20:42:20Z",
      "totalStrings": 12000,
      "translatedStrings": 11400,
      "url": "https://github.com/search?q=WordPress language:Swedish",
      "langCode": "sv"
    },
    {
      "name": "VLC media player",
      "category": "media",
      "platform": "transifex",
      "stars": 12000,
      "swedishProgress": 95,
      "quality": 9,
      "lastUpdate": "2026-03-20T20:42:20Z",
      "totalStrings": 5000,
      "translatedStrings": 4750,
      "url": "https://github.com/search?q=VLC media player language:Swedish",
      "langCode": "sv"
    },
    {
      "name": "LibreOffice",
      "category": "desktop",
      "platform": "weblate",
      "stars": 3500,
      "swedishProgress": 95,
      "quality": 9,
      "lastUpdate": "2026-03-20T20:42:20Z",
      "totalStrings": 35000,
      "translatedStrings": 33250,
      "url": "https://github.com/search?q=LibreOffice language:Swedish",
      "langCode": "sv"
    },
    {
      "name": "Ubuntu",
      "category": "system",
      "platform": "launchpad",
      "stars": 0,
      "swedishProgress": 95,
      "quality": 9,
      "lastUpdate": "2026-03-20T20:42:20Z",
      "totalStrings": 50000,
      "translatedStrings": 47500,
      "url": "https://github.com/search?q=Ubuntu language:Swedish",
      "langCode": "sv"
    },
    {
      "name": "gnome-calendar",
      "category": "desktop",
      "platform": "gnome",
      "stars": 0,
      "swedishProgress": 95,
      "quality": 9,
      "lastUpdate": "2026-03-20T20:42:20Z",
      "totalStrings": 1895,
      "translatedStrings": 1800,
      "url": "https://l10n.gnome.org/module/gnome-calendar/",
      "langCode": "sv"
    },
    {
      "name": "atk",
      "category": "desktop",
      "platform": "gnome",
      "stars": 0,
      "swedishProgress": 95,
      "quality": 9,
      "lastUpdate": "2026-03-20T20:42:20Z",
      "totalStrings": 1305,
      "translatedStrings": 1239,
      "url": "https://l10n.gnome.org/module/atk/",
      "langCode": "sv"
    },
    {
      "name": "plasma-desktop",
      "category": "desktop",
      "platform": "kde",
      "stars": 0,
      "swedishProgress": 95,
      "quality": 8,
      "lastUpdate": "2026-03-20T20:42:20Z",
      "totalStrings": 1655,
      "translatedStrings": 1572,
      "url": "https://l10n.kde.org/stats/gui/trunk-kf6/plasma-desktop/sv/",
      "langCode": "sv"
    },
    {
      "name": "csv-to-markdown",
      "category": "desktop",
      "platform": "github",
      "stars": 0,
      "swedishProgress": 95,
      "quality": 7,
      "lastUpdate": "2026-03-20T20:42:25Z",
      "totalStrings": 770,
      "translatedStrings": 731,
      "url": "https://github.com/beenotung/csv-to-markdown",
      "langCode": "sv"
    },
    {
      "name": "Bradock",
      "category": "desktop",
      "platform": "github",
      "stars": 0,
      "swedishProgress": 95,
      "quality": 7,
      "lastUpdate": "2026-03-20T20:42:28Z",
      "totalStrings": 620,
      "translatedStrings": 589,
      "url": "https://github.com/bradskdg3/Bradock",
      "langCode": "sv"
    },
    {
      "name": "gen-format",
      "category": "web",
      "platform": "github",
      "stars": 0,
      "swedishProgress": 95,
      "quality": 7,
      "lastUpdate": "2026-03-20T20:42:30Z",
      "totalStrings": 245,
      "translatedStrings": 232,
      "url": "https://github.com/tremho/gen-format",
      "langCode": "sv"
    },
    {
      "name": "Thunderbird",
      "category": "desktop",
      "platform": "pontoon",
      "stars": 0,
      "swedishProgress": 95,
      "quality": 9,
      "lastUpdate": "2026-03-20T20:42:32Z",
      "totalStrings": 8000,
      "translatedStrings": 7600,
      "url": "https://pontoon.mozilla.org/sv-SE/thunderbird/",
      "langCode": "sv-SE"
    },
    {
      "name": "GNOME Shell",
      "category": "system",
      "platform": "gnome",
      "stars": 1500,
      "swedishProgress": 94,
      "quality": 9,
      "lastUpdate": "2026-03-20T20:42:20Z",
      "totalStrings": 2500,
      "translatedStrings": 2350,
      "url": "https://github.com/search?q=GNOME Shell language:Swedish",
      "langCode": "sv"
    },
    {
      "name": "evolution",
      "category": "desktop",
      "platform": "gnome",
      "stars": 0,
      "swedishProgress": 94,
      "quality": 9,
      "lastUpdate": "2026-03-20T20:42:20Z",
      "totalStrings": 1864,
      "translatedStrings": 1752,
      "url": "https://l10n.gnome.org/module/evolution/",
      "langCode": "sv"
    },
    {
      "name": "systemsettings",
      "category": "desktop",
      "platform": "kde",
      "stars": 0,
      "swedishProgress": 94,
      "quality": 8,
      "lastUpdate": "2026-03-20T20:42:20Z",
      "totalStrings": 1174,
      "translatedStrings": 1103,
      "url": "https://l10n.kde.org/stats/gui/trunk-kf6/systemsettings/sv/",
      "langCode": "sv"
    },
    {
      "name": "aliprice",
      "category": "desktop",
      "platform": "github",
      "stars": 0,
      "swedishProgress": 94,
      "quality": 7,
      "lastUpdate": "2026-03-20T20:42:23Z",
      "totalStrings": 294,
      "translatedStrings": 276,
      "url": "https://github.com/common-repository/aliprice",
      "langCode": "sv"
    },
    {
      "name": "jsforce",
      "category": "web",
      "platform": "github",
      "stars": 0,
      "swedishProgress": 94,
      "quality": 7,
      "lastUpdate": "2026-03-20T20:42:25Z",
      "totalStrings": 319,
      "translatedStrings": 299,
      "url": "https://github.com/jsforce/jsforce",
      "langCode": "sv"
    },
    {
      "name": "xtoool-redirecter",
      "category": "desktop",
      "platform": "github",
      "stars": 0,
      "swedishProgress": 94,
      "quality": 7,
      "lastUpdate": "2026-03-20T20:42:28Z",
      "totalStrings": 594,
      "translatedStrings": 558,
      "url": "https://github.com/common-repository/xtoool-redirecter",
      "langCode": "sv"
    },
    {
      "name": "webserver",
      "category": "web",
      "platform": "github",
      "stars": 0,
      "swedishProgress": 93,
      "quality": 7,
      "lastUpdate": "2026-03-20T20:42:23Z",
      "totalStrings": 918,
      "translatedStrings": 853,
      "url": "https://github.com/cherokee/webserver",
      "langCode": "sv"
    },
    {
      "name": "open-source-jobs",
      "category": "desktop",
      "platform": "github",
      "stars": 0,
      "swedishProgress": 93,
      "quality": 7,
      "lastUpdate": "2026-03-20T20:42:25Z",
      "totalStrings": 718,
      "translatedStrings": 667,
      "url": "https://github.com/timqian/open-source-jobs",
      "langCode": "sv"
    },
    {
      "name": "serbianorthodox.github.io",
      "category": "development",
      "platform": "github",
      "stars": 0,
      "swedishProgress": 93,
      "quality": 7,
      "lastUpdate": "2026-03-20T20:42:30Z",
      "totalStrings": 918,
      "translatedStrings": 853,
      "url": "https://github.com/serbianorthodox/serbianorthodox.github.io",
      "langCode": "sv"
    },
    {
      "name": "SemanticCite",
      "category": "desktop",
      "platform": "github",
      "stars": 0,
      "swedishProgress": 93,
      "quality": 7,
      "lastUpdate": "2026-03-20T20:42:30Z",
      "totalStrings": 743,
      "translatedStrings": 690,
      "url": "https://github.com/SemanticMediaWiki/SemanticCite",
      "langCode": "sv"
    },
    {
      "name": "mediawiki-skins-BlueSpiceDiscovery",
      "category": "web",
      "platform": "github",
      "stars": 0,
      "swedishProgress": 93,
      "quality": 7,
      "lastUpdate": "2026-03-20T20:42:30Z",
      "totalStrings": 468,
      "translatedStrings": 435,
      "url": "https://github.com/wikimedia/mediawiki-skins-BlueSpiceDiscovery",
      "langCode": "sv"
    },
    {
      "name": "KeePassXC",
      "category": "security",
      "platform": "transifex",
      "stars": 19000,
      "swedishProgress": 92,
      "quality": 9,
      "lastUpdate": "2026-03-20T20:42:20Z",
      "totalStrings": 1500,
      "translatedStrings": 1380,
      "url": "https://github.com/search?q=KeePassXC language:Swedish",
      "langCode": "sv"
    },
    {
      "name": "phpMyAdmin",
      "category": "web",
      "platform": "weblate",
      "stars": 6000,
      "swedishProgress": 92,
      "quality": 9,
      "lastUpdate": "2026-03-20T20:42:20Z",
      "totalStrings": 4000,
      "translatedStrings": 3680,
      "url": "https://github.com/search?q=phpMyAdmin language:Swedish",
      "langCode": "sv"
    },
    {
      "name": "GIMP",
      "category": "media",
      "platform": "gnome",
      "stars": 4000,
      "swedishProgress": 92,
      "quality": 9,
      "lastUpdate": "2026-03-20T20:42:20Z",
      "totalStrings": 8000,
      "translatedStrings": 7360,
      "url": "https://github.com/search?q=GIMP language:Swedish",
      "langCode": "sv"
    },
    {
      "name": "totem",
      "category": "desktop",
      "platform": "gnome",
      "stars": 0,
      "swedishProgress": 92,
      "quality": 9,
      "lastUpdate": "2026-03-20T20:42:20Z",
      "totalStrings": 1412,
      "translatedStrings": 1299,
      "url": "https://l10n.gnome.org/module/totem/",
      "langCode": "sv"
    },
    {
      "name": "epiphany",
      "category": "desktop",
      "platform": "gnome",
      "stars": 0,
      "swedishProgress": 92,
      "quality": 9,
      "lastUpdate": "2026-03-20T20:42:20Z",
      "totalStrings": 2077,
      "translatedStrings": 1910,
      "url": "https://l10n.gnome.org/module/epiphany/",
      "langCode": "sv"
    },
    {
      "name": "WordPress-Avatar",
      "category": "desktop",
      "platform": "github",
      "stars": 0,
      "swedishProgress": 92,
      "quality": 7,
      "lastUpdate": "2026-03-20T20:42:23Z",
      "totalStrings": 967,
      "translatedStrings": 889,
      "url": "https://github.com/pontusab/WordPress-Avatar",
      "langCode": "sv"
    },
    {
      "name": "translations",
      "category": "development",
      "platform": "github",
      "stars": 0,
      "swedishProgress": 92,
      "quality": 7,
      "lastUpdate": "2026-03-20T20:42:23Z",
      "totalStrings": 942,
      "translatedStrings": 866,
      "url": "https://github.com/TortoiseGit/translations",
      "langCode": "sv"
    },
    {
      "name": "ChuanhuChatGPT",
      "category": "web",
      "platform": "github",
      "stars": 0,
      "swedishProgress": 92,
      "quality": 7,
      "lastUpdate": "2026-03-20T20:42:28Z",
      "totalStrings": 692,
      "translatedStrings": 636,
      "url": "https://github.com/GaiZhenbiao/ChuanhuChatGPT",
      "langCode": "sv"
    },
    {
      "name": "hu",
      "category": "desktop",
      "platform": "github",
      "stars": 0,
      "swedishProgress": 92,
      "quality": 7,
      "lastUpdate": "2026-03-20T20:42:28Z",
      "totalStrings": 642,
      "translatedStrings": 590,
      "url": "https://github.com/dakaca007/hu",
      "langCode": "sv"
    },
    {
      "name": "SimpleTooltip",
      "category": "desktop",
      "platform": "github",
      "stars": 0,
      "swedishProgress": 92,
      "quality": 7,
      "lastUpdate": "2026-03-20T20:42:30Z",
      "totalStrings": 367,
      "translatedStrings": 337,
      "url": "https://github.com/Universal-Omega/SimpleTooltip",
      "langCode": "sv"
    },
    {
      "name": "6402-Project",
      "category": "web",
      "platform": "github",
      "stars": 0,
      "swedishProgress": 92,
      "quality": 7,
      "lastUpdate": "2026-03-20T20:42:30Z",
      "totalStrings": 367,
      "translatedStrings": 337,
      "url": "https://github.com/WMCO-C0/6402-Project",
      "langCode": "sv"
    },
    {
      "name": "Firefox for Android",
      "category": "mobile",
      "platform": "pontoon",
      "stars": 0,
      "swedishProgress": 92,
      "quality": 9,
      "lastUpdate": "2026-03-20T20:42:32Z",
      "totalStrings": 5000,
      "translatedStrings": 4600,
      "url": "https://pontoon.mozilla.org/sv-SE/firefox-for-android/",
      "langCode": "sv-SE"
    },
    {
      "name": "gnome-system-monitor",
      "category": "desktop",
      "platform": "gnome",
      "stars": 0,
      "swedishProgress": 91,
      "quality": 9,
      "lastUpdate": "2026-03-20T20:42:20Z",
      "totalStrings": 531,
      "translatedStrings": 483,
      "url": "https://l10n.gnome.org/module/gnome-system-monitor/",
      "langCode": "sv"
    },
    {
      "name": "gnome-photos",
      "category": "desktop",
      "platform": "gnome",
      "stars": 0,
      "swedishProgress": 91,
      "quality": 9,
      "lastUpdate": "2026-03-20T20:42:20Z",
      "totalStrings": 901,
      "translatedStrings": 819,
      "url": "https://l10n.gnome.org/module/gnome-photos/",
      "langCode": "sv"
    },
    {
      "name": "pango",
      "category": "desktop",
      "platform": "gnome",
      "stars": 0,
      "swedishProgress": 91,
      "quality": 9,
      "lastUpdate": "2026-03-20T20:42:20Z",
      "totalStrings": 1846,
      "translatedStrings": 1679,
      "url": "https://l10n.gnome.org/module/pango/",
      "langCode": "sv"
    },
    {
      "name": "einakter",
      "category": "games",
      "platform": "github",
      "stars": 0,
      "swedishProgress": 91,
      "quality": 7,
      "lastUpdate": "2026-03-20T20:42:25Z",
      "totalStrings": 341,
      "translatedStrings": 310,
      "url": "https://github.com/dracor-org/einakter",
      "langCode": "sv"
    },
    {
      "name": "VS Code",
      "category": "development",
      "platform": "github",
      "stars": 150000,
      "swedishProgress": 90,
      "quality": 9,
      "lastUpdate": "2026-03-20T20:42:20Z",
      "totalStrings": 8000,
      "translatedStrings": 7200,
      "url": "https://github.com/search?q=VS Code language:Swedish",
      "langCode": "sv"
    },
    {
      "name": "Drupal",
      "category": "web",
      "platform": "drupal",
      "stars": 4000,
      "swedishProgress": 90,
      "quality": 9,
      "lastUpdate": "2026-03-20T20:42:20Z",
      "totalStrings": 15000,
      "translatedStrings": 13500,
      "url": "https://github.com/search?q=Drupal language:Swedish",
      "langCode": "sv"
    },
    {
      "name": "SuperTux",
      "category": "games",
      "platform": "transifex",
      "stars": 2000,
      "swedishProgress": 90,
      "quality": 9,
      "lastUpdate": "2026-03-20T20:42:20Z",
      "totalStrings": 800,
      "translatedStrings": 720,
      "url": "https://github.com/search?q=SuperTux language:Swedish",
      "langCode": "sv"
    },
    {
      "name": "Fedora",
      "category": "system",
      "platform": "weblate",
      "stars": 0,
      "swedishProgress": 90,
      "quality": 9,
      "lastUpdate": "2026-03-20T20:42:20Z",
      "totalStrings": 30000,
      "translatedStrings": 27000,
      "url": "https://github.com/search?q=Fedora language:Swedish",
      "langCode": "sv"
    },
    {
      "name": "okular",
      "category": "desktop",
      "platform": "kde",
      "stars": 0,
      "swedishProgress": 90,
      "quality": 8,
      "lastUpdate": "2026-03-20T20:42:20Z",
      "totalStrings": 1310,
      "translatedStrings": 1179,
      "url": "https://l10n.kde.org/stats/gui/trunk-kf6/okular/sv/",
      "langCode": "sv"
    },
    {
      "name": "wp-mailchimp",
      "category": "desktop",
      "platform": "github",
      "stars": 0,
      "swedishProgress": 90,
      "quality": 7,
      "lastUpdate": "2026-03-20T20:42:23Z",
      "totalStrings": 815,
      "translatedStrings": 733,
      "url": "https://github.com/crowdfavorite/wp-mailchimp",
      "langCode": "sv"
    },
    {
      "name": "libNyaruko_TS",
      "category": "desktop",
      "platform": "github",
      "stars": 0,
      "swedishProgress": 90,
      "quality": 7,
      "lastUpdate": "2026-03-20T20:42:25Z",
      "totalStrings": 640,
      "translatedStrings": 576,
      "url": "https://github.com/kagurazakayashi/libNyaruko_TS",
      "langCode": "sv"
    },
    {
      "name": "LdapAuthentication",
      "category": "security",
      "platform": "github",
      "stars": 0,
      "swedishProgress": 90,
      "quality": 7,
      "lastUpdate": "2026-03-20T20:42:30Z",
      "totalStrings": 865,
      "translatedStrings": 778,
      "url": "https://github.com/miraheze/LdapAuthentication",
      "langCode": "sv"
    },
    {
      "name": "Firefox Focus",
      "category": "mobile",
      "platform": "pontoon",
      "stars": 0,
      "swedishProgress": 90,
      "quality": 9,
      "lastUpdate": "2026-03-20T20:42:32Z",
      "totalStrings": 800,
      "translatedStrings": 720,
      "url": "https://pontoon.mozilla.org/sv-SE/firefox-focus/",
      "langCode": "sv-SE"
    },
    {
      "name": "gnome-disk-utility",
      "category": "desktop",
      "platform": "gnome",
      "stars": 0,
      "swedishProgress": 89,
      "quality": 9,
      "lastUpdate": "2026-03-20T20:42:20Z",
      "totalStrings": 1439,
      "translatedStrings": 1280,
      "url": "https://l10n.gnome.org/module/gnome-disk-utility/",
      "langCode": "sv"
    },
    {
      "name": "gnome-software",
      "category": "desktop",
      "platform": "gnome",
      "stars": 0,
      "swedishProgress": 89,
      "quality": 9,
      "lastUpdate": "2026-03-20T20:42:20Z",
      "totalStrings": 1674,
      "translatedStrings": 1489,
      "url": "https://l10n.gnome.org/module/gnome-software/",
      "langCode": "sv"
    },
    {
      "name": "ktorrent",
      "category": "desktop",
      "platform": "kde",
      "stars": 0,
      "swedishProgress": 89,
      "quality": 8,
      "lastUpdate": "2026-03-20T20:42:20Z",
      "totalStrings": 1529,
      "translatedStrings": 1360,
      "url": "https://l10n.kde.org/stats/gui/trunk-kf6/ktorrent/sv/",
      "langCode": "sv"
    },
    {
      "name": "stemjs",
      "category": "web",
      "platform": "github",
      "stars": 0,
      "swedishProgress": 89,
      "quality": 7,
      "lastUpdate": "2026-03-20T20:42:25Z",
      "totalStrings": 589,
      "translatedStrings": 524,
      "url": "https://github.com/mciucu/stemjs",
      "langCode": "sv"
    },
    {
      "name": "nmea-simple",
      "category": "web",
      "platform": "github",
      "stars": 0,
      "swedishProgress": 89,
      "quality": 7,
      "lastUpdate": "2026-03-20T20:42:25Z",
      "totalStrings": 239,
      "translatedStrings": 212,
      "url": "https://github.com/101100/nmea-simple",
      "langCode": "sv"
    },
    {
      "name": "Nextcloud",
      "category": "web",
      "platform": "transifex",
      "stars": 25000,
      "swedishProgress": 88,
      "quality": 8,
      "lastUpdate": "2026-03-20T20:42:20Z",
      "totalStrings": 8000,
      "translatedStrings": 7040,
      "url": "https://github.com/search?q=Nextcloud language:Swedish",
      "langCode": "sv"
    },
    {
      "name": "F-Droid",
      "category": "mobile",
      "platform": "weblate",
      "stars": 11000,
      "swedishProgress": 88,
      "quality": 8,
      "lastUpdate": "2026-03-20T20:42:20Z",
      "totalStrings": 800,
      "translatedStrings": 704,
      "url": "https://github.com/search?q=F-Droid language:Swedish",
      "langCode": "sv"
    },
    {
      "name": "Blender",
      "category": "media",
      "platform": "weblate",
      "stars": 10000,
      "swedishProgress": 88,
      "quality": 8,
      "lastUpdate": "2026-03-20T20:42:20Z",
      "totalStrings": 12000,
      "translatedStrings": 10560,
      "url": "https://github.com/search?q=Blender language:Swedish",
      "langCode": "sv"
    },
    {
      "name": "Minetest",
      "category": "games",
      "platform": "weblate",
      "stars": 9000,
      "swedishProgress": 88,
      "quality": 8,
      "lastUpdate": "2026-03-20T20:42:20Z",
      "totalStrings": 2500,
      "translatedStrings": 2200,
      "url": "https://github.com/search?q=Minetest language:Swedish",
      "langCode": "sv"
    },
    {
      "name": "Debian",
      "category": "system",
      "platform": "debian",
      "stars": 0,
      "swedishProgress": 88,
      "quality": 8,
      "lastUpdate": "2026-03-20T20:42:20Z",
      "totalStrings": 40000,
      "translatedStrings": 35200,
      "url": "https://github.com/search?q=Debian language:Swedish",
      "langCode": "sv"
    },
    {
      "name": "gnome-contacts",
      "category": "desktop",
      "platform": "gnome",
      "stars": 0,
      "swedishProgress": 88,
      "quality": 9,
      "lastUpdate": "2026-03-20T20:42:20Z",
      "totalStrings": 2248,
      "translatedStrings": 1978,
      "url": "https://l10n.gnome.org/module/gnome-contacts/",
      "langCode": "sv"
    },
    {
      "name": "Common Voice",
      "category": "web",
      "platform": "pontoon",
      "stars": 0,
      "swedishProgress": 88,
      "quality": 9,
      "lastUpdate": "2026-03-20T20:42:32Z",
      "totalStrings": 2000,
      "translatedStrings": 1760,
      "url": "https://pontoon.mozilla.org/sv-SE/common-voice/",
      "langCode": "sv-SE"
    },
    {
      "name": "nautilus",
      "category": "desktop",
      "platform": "gnome",
      "stars": 0,
      "swedishProgress": 87,
      "quality": 9,
      "lastUpdate": "2026-03-20T20:42:20Z",
      "totalStrings": 1037,
      "translatedStrings": 902,
      "url": "https://l10n.gnome.org/module/nautilus/",
      "langCode": "sv"
    },
    {
      "name": "ark",
      "category": "desktop",
      "platform": "kde",
      "stars": 0,
      "swedishProgress": 87,
      "quality": 8,
      "lastUpdate": "2026-03-20T20:42:20Z",
      "totalStrings": 1007,
      "translatedStrings": 876,
      "url": "https://l10n.kde.org/stats/gui/trunk-kf6/ark/sv/",
      "langCode": "sv"
    },
    {
      "name": "gnu_childsplay",
      "category": "games",
      "platform": "github",
      "stars": 0,
      "swedishProgress": 87,
      "quality": 7,
      "lastUpdate": "2026-03-20T20:42:23Z",
      "totalStrings": 687,
      "translatedStrings": 597,
      "url": "https://github.com/gitGNU/gnu_childsplay",
      "langCode": "sv"
    },
    {
      "name": "sonR",
      "category": "desktop",
      "platform": "github",
      "stars": 0,
      "swedishProgress": 87,
      "quality": 7,
      "lastUpdate": "2026-03-20T20:42:25Z",
      "totalStrings": 687,
      "translatedStrings": 597,
      "url": "https://github.com/arnejohannesholmin/sonR",
      "langCode": "sv"
    },
    {
      "name": "gnome-shell",
      "category": "desktop",
      "platform": "gnome",
      "stars": 0,
      "swedishProgress": 86,
      "quality": 9,
      "lastUpdate": "2026-03-20T20:42:20Z",
      "totalStrings": 706,
      "translatedStrings": 607,
      "url": "https://l10n.gnome.org/module/gnome-shell/",
      "langCode": "sv"
    },
    {
      "name": "kate",
      "category": "desktop",
      "platform": "kde",
      "stars": 0,
      "swedishProgress": 86,
      "quality": 8,
      "lastUpdate": "2026-03-20T20:42:20Z",
      "totalStrings": 1506,
      "translatedStrings": 1295,
      "url": "https://l10n.kde.org/stats/gui/trunk-kf6/kate/sv/",
      "langCode": "sv"
    },
    {
      "name": "kdenlive",
      "category": "desktop",
      "platform": "kde",
      "stars": 0,
      "swedishProgress": 86,
      "quality": 8,
      "lastUpdate": "2026-03-20T20:42:20Z",
      "totalStrings": 386,
      "translatedStrings": 331,
      "url": "https://l10n.kde.org/stats/gui/trunk-kf6/kdenlive/sv/",
      "langCode": "sv"
    },
    {
      "name": "kcalc",
      "category": "desktop",
      "platform": "kde",
      "stars": 0,
      "swedishProgress": 86,
      "quality": 8,
      "lastUpdate": "2026-03-20T20:42:20Z",
      "totalStrings": 1566,
      "translatedStrings": 1346,
      "url": "https://l10n.kde.org/stats/gui/trunk-kf6/kcalc/sv/",
      "langCode": "sv"
    },
    {
      "name": "krunner",
      "category": "desktop",
      "platform": "kde",
      "stars": 0,
      "swedishProgress": 86,
      "quality": 8,
      "lastUpdate": "2026-03-20T20:42:20Z",
      "totalStrings": 906,
      "translatedStrings": 779,
      "url": "https://l10n.kde.org/stats/gui/trunk-kf6/krunner/sv/",
      "langCode": "sv"
    },
    {
      "name": "EventCalendar3",
      "category": "desktop",
      "platform": "github",
      "stars": 0,
      "swedishProgress": 86,
      "quality": 7,
      "lastUpdate": "2026-03-20T20:42:23Z",
      "totalStrings": 661,
      "translatedStrings": 568,
      "url": "https://github.com/upekshapriya/EventCalendar3",
      "langCode": "sv"
    },
    {
      "name": "J90280.05.analysis",
      "category": "games",
      "platform": "github",
      "stars": 0,
      "swedishProgress": 86,
      "quality": 7,
      "lastUpdate": "2026-03-20T20:42:25Z",
      "totalStrings": 261,
      "translatedStrings": 224,
      "url": "https://github.com/jlaustill/J90280.05.analysis",
      "langCode": "sv"
    },
    {
      "name": "Git",
      "category": "development",
      "platform": "tp",
      "stars": 50000,
      "swedishProgress": 85,
      "quality": 8,
      "lastUpdate": "2026-03-20T20:42:20Z",
      "totalStrings": 2500,
      "translatedStrings": 2125,
      "url": "https://github.com/search?q=Git language:Swedish",
      "langCode": "sv"
    },
    {
      "name": "K-9 Mail",
      "category": "mobile",
      "platform": "transifex",
      "stars": 9000,
      "swedishProgress": 85,
      "quality": 8,
      "lastUpdate": "2026-03-20T20:42:20Z",
      "totalStrings": 1200,
      "translatedStrings": 1020,
      "url": "https://github.com/search?q=K-9 Mail language:Swedish",
      "langCode": "sv"
    },
    {
      "name": "Wireshark",
      "category": "security",
      "platform": "weblate",
      "stars": 7000,
      "swedishProgress": 85,
      "quality": 8,
      "lastUpdate": "2026-03-20T20:42:20Z",
      "totalStrings": 8000,
      "translatedStrings": 6800,
      "url": "https://github.com/search?q=Wireshark language:Swedish",
      "langCode": "sv"
    },
    {
      "name": "Battle for Wesnoth",
      "category": "games",
      "platform": "github",
      "stars": 4500,
      "swedishProgress": 85,
      "quality": 8,
      "lastUpdate": "2026-03-20T20:42:20Z",
      "totalStrings": 25000,
      "translatedStrings": 21250,
      "url": "https://github.com/search?q=Battle for Wesnoth language:Swedish",
      "langCode": "sv"
    },
    {
      "name": "Inkscape",
      "category": "media",
      "platform": "weblate",
      "stars": 3000,
      "swedishProgress": 85,
      "quality": 8,
      "lastUpdate": "2026-03-20T20:42:20Z",
      "totalStrings": 6000,
      "translatedStrings": 5100,
      "url": "https://github.com/search?q=Inkscape language:Swedish",
      "langCode": "sv"
    },
    {
      "name": "gnome-control-center",
      "category": "desktop",
      "platform": "gnome",
      "stars": 0,
      "swedishProgress": 85,
      "quality": 9,
      "lastUpdate": "2026-03-20T20:42:20Z",
      "totalStrings": 2435,
      "translatedStrings": 2069,
      "url": "https://l10n.gnome.org/module/gnome-control-center/",
      "langCode": "sv"
    },
    {
      "name": "gedit",
      "category": "desktop",
      "platform": "gnome",
      "stars": 0,
      "swedishProgress": 85,
      "quality": 9,
      "lastUpdate": "2026-03-20T20:42:20Z",
      "totalStrings": 835,
      "translatedStrings": 709,
      "url": "https://l10n.gnome.org/module/gedit/",
      "langCode": "sv"
    },
    {
      "name": "gnome-calculator",
      "category": "desktop",
      "platform": "gnome",
      "stars": 0,
      "swedishProgress": 85,
      "quality": 9,
      "lastUpdate": "2026-03-20T20:42:20Z",
      "totalStrings": 1400,
      "translatedStrings": 1190,
      "url": "https://l10n.gnome.org/module/gnome-calculator/",
      "langCode": "sv"
    },
    {
      "name": "gnome-terminal",
      "category": "desktop",
      "platform": "gnome",
      "stars": 0,
      "swedishProgress": 85,
      "quality": 9,
      "lastUpdate": "2026-03-20T20:42:20Z",
      "totalStrings": 1950,
      "translatedStrings": 1657,
      "url": "https://l10n.gnome.org/module/gnome-terminal/",
      "langCode": "sv"
    },
    {
      "name": "gtk",
      "category": "desktop",
      "platform": "gnome",
      "stars": 0,
      "swedishProgress": 85,
      "quality": 9,
      "lastUpdate": "2026-03-20T20:42:20Z",
      "totalStrings": 955,
      "translatedStrings": 811,
      "url": "https://l10n.gnome.org/module/gtk/",
      "langCode": "sv"
    },
    {
      "name": "konsole",
      "category": "desktop",
      "platform": "kde",
      "stars": 0,
      "swedishProgress": 85,
      "quality": 8,
      "lastUpdate": "2026-03-20T20:42:20Z",
      "totalStrings": 345,
      "translatedStrings": 293,
      "url": "https://l10n.kde.org/stats/gui/trunk-kf6/konsole/sv/",
      "langCode": "sv"
    },
    {
      "name": "k3b",
      "category": "desktop",
      "platform": "kde",
      "stars": 0,
      "swedishProgress": 85,
      "quality": 8,
      "lastUpdate": "2026-03-20T20:42:20Z",
      "totalStrings": 1285,
      "translatedStrings": 1092,
      "url": "https://l10n.kde.org/stats/gui/trunk-kf6/k3b/sv/",
      "langCode": "sv"
    },
    {
      "name": "spectacle",
      "category": "desktop",
      "platform": "kde",
      "stars": 0,
      "swedishProgress": 85,
      "quality": 8,
      "lastUpdate": "2026-03-20T20:42:20Z",
      "totalStrings": 745,
      "translatedStrings": 633,
      "url": "https://l10n.kde.org/stats/gui/trunk-kf6/spectacle/sv/",
      "langCode": "sv"
    },
    {
      "name": "WurgerKing",
      "category": "web",
      "platform": "github",
      "stars": 0,
      "swedishProgress": 85,
      "quality": 7,
      "lastUpdate": "2026-03-20T20:42:23Z",
      "totalStrings": 910,
      "translatedStrings": 773,
      "url": "https://github.com/WebFreak001/WurgerKing",
      "langCode": "sv"
    },
    {
      "name": "mediawiki-extensions-DarkMode",
      "category": "web",
      "platform": "github",
      "stars": 0,
      "swedishProgress": 85,
      "quality": 7,
      "lastUpdate": "2026-03-20T20:42:30Z",
      "totalStrings": 510,
      "translatedStrings": 433,
      "url": "https://github.com/wikimedia/mediawiki-extensions-DarkMode",
      "langCode": "sv"
    },
    {
      "name": "Duplicator",
      "category": "media",
      "platform": "github",
      "stars": 0,
      "swedishProgress": 85,
      "quality": 7,
      "lastUpdate": "2026-03-20T20:42:30Z",
      "totalStrings": 335,
      "translatedStrings": 284,
      "url": "https://github.com/mediawiki4intranet/Duplicator",
      "langCode": "sv"
    },
    {
      "name": "MDN Web Docs",
      "category": "web",
      "platform": "pontoon",
      "stars": 0,
      "swedishProgress": 85,
      "quality": 9,
      "lastUpdate": "2026-03-20T20:42:32Z",
      "totalStrings": 12000,
      "translatedStrings": 10200,
      "url": "https://pontoon.mozilla.org/sv-SE/mdn-web-docs/",
      "langCode": "sv-SE"
    },
    {
      "name": "calligra",
      "category": "desktop",
      "platform": "kde",
      "stars": 0,
      "swedishProgress": 84,
      "quality": 8,
      "lastUpdate": "2026-03-20T20:42:20Z",
      "totalStrings": 1124,
      "translatedStrings": 944,
      "url": "https://l10n.kde.org/stats/gui/trunk-kf6/calligra/sv/",
      "langCode": "sv"
    },
    {
      "name": "mad3",
      "category": "web",
      "platform": "github",
      "stars": 0,
      "swedishProgress": 84,
      "quality": 7,
      "lastUpdate": "2026-03-20T20:42:25Z",
      "totalStrings": 934,
      "translatedStrings": 784,
      "url": "https://github.com/icdocsoc/mad3",
      "langCode": "sv"
    },
    {
      "name": "test_chatbot",
      "category": "desktop",
      "platform": "github",
      "stars": 0,
      "swedishProgress": 83,
      "quality": 7,
      "lastUpdate": "2026-03-20T20:42:28Z",
      "totalStrings": 558,
      "translatedStrings": 463,
      "url": "https://github.com/JuneYaooo/test_chatbot",
      "langCode": "sv"
    },
    {
      "name": "desktop",
      "category": "desktop",
      "platform": "github",
      "stars": 0,
      "swedishProgress": 83,
      "quality": 7,
      "lastUpdate": "2026-03-20T20:42:30Z",
      "totalStrings": 458,
      "translatedStrings": 380,
      "url": "https://github.com/mattermost/desktop",
      "langCode": "sv"
    },
    {
      "name": "wikipedia-preview",
      "category": "desktop",
      "platform": "github",
      "stars": 0,
      "swedishProgress": 83,
      "quality": 7,
      "lastUpdate": "2026-03-20T20:42:30Z",
      "totalStrings": 583,
      "translatedStrings": 483,
      "url": "https://github.com/wikimedia/wikipedia-preview",
      "langCode": "sv"
    },
    {
      "name": "mediawiki-extensions-EmailCapture",
      "category": "web",
      "platform": "github",
      "stars": 0,
      "swedishProgress": 83,
      "quality": 7,
      "lastUpdate": "2026-03-20T20:42:30Z",
      "totalStrings": 758,
      "translatedStrings": 629,
      "url": "https://github.com/wikimedia/mediawiki-extensions-EmailCapture",
      "langCode": "sv"
    },
    {
      "name": "Godot Engine",
      "category": "games",
      "platform": "weblate",
      "stars": 85000,
      "swedishProgress": 82,
      "quality": 8,
      "lastUpdate": "2026-03-20T20:42:20Z",
      "totalStrings": 15000,
      "translatedStrings": 12300,
      "url": "https://github.com/search?q=Godot Engine language:Swedish",
      "langCode": "sv"
    },
    {
      "name": "Audacity",
      "category": "media",
      "platform": "github",
      "stars": 11000,
      "swedishProgress": 82,
      "quality": 8,
      "lastUpdate": "2026-03-20T20:42:20Z",
      "totalStrings": 3000,
      "translatedStrings": 2460,
      "url": "https://github.com/search?q=Audacity language:Swedish",
      "langCode": "sv"
    },
    {
      "name": "OwnCloud",
      "category": "web",
      "platform": "transifex",
      "stars": 8000,
      "swedishProgress": 82,
      "quality": 8,
      "lastUpdate": "2026-03-20T20:42:20Z",
      "totalStrings": 6000,
      "translatedStrings": 4920,
      "url": "https://github.com/search?q=OwnCloud language:Swedish",
      "langCode": "sv"
    },
    {
      "name": "govintranet-free",
      "category": "development",
      "platform": "github",
      "stars": 0,
      "swedishProgress": 82,
      "quality": 7,
      "lastUpdate": "2026-03-20T20:42:23Z",
      "totalStrings": 582,
      "translatedStrings": 477,
      "url": "https://github.com/lukeoatham/govintranet-free",
      "langCode": "sv"
    },
    {
      "name": "issuem",
      "category": "web",
      "platform": "github",
      "stars": 0,
      "swedishProgress": 82,
      "quality": 7,
      "lastUpdate": "2026-03-20T20:42:23Z",
      "totalStrings": 707,
      "translatedStrings": 579,
      "url": "https://github.com/zeen101/issuem",
      "langCode": "sv"
    },
    {
      "name": "kmix",
      "category": "desktop",
      "platform": "kde",
      "stars": 0,
      "swedishProgress": 81,
      "quality": 8,
      "lastUpdate": "2026-03-20T20:42:20Z",
      "totalStrings": 561,
      "translatedStrings": 454,
      "url": "https://l10n.kde.org/stats/gui/trunk-kf6/kmix/sv/",
      "langCode": "sv"
    },
    {
      "name": "excel-JS",
      "category": "desktop",
      "platform": "github",
      "stars": 0,
      "swedishProgress": 81,
      "quality": 7,
      "lastUpdate": "2026-03-20T20:42:25Z",
      "totalStrings": 981,
      "translatedStrings": 794,
      "url": "https://github.com/alirezashon/excel-JS",
      "langCode": "sv"
    },
    {
      "name": "lava",
      "category": "desktop",
      "platform": "github",
      "stars": 0,
      "swedishProgress": 81,
      "quality": 7,
      "lastUpdate": "2026-03-20T20:42:28Z",
      "totalStrings": 331,
      "translatedStrings": 268,
      "url": "https://github.com/Nat1anWasTaken/lava",
      "langCode": "sv"
    },
    {
      "name": "MinistryX",
      "category": "web",
      "platform": "github",
      "stars": 0,
      "swedishProgress": 81,
      "quality": 7,
      "lastUpdate": "2026-03-20T20:42:28Z",
      "totalStrings": 331,
      "translatedStrings": 268,
      "url": "https://github.com/CrazyCoder254/MinistryX",
      "langCode": "sv"
    },
    {
      "name": "ZhongjiaoGPT",
      "category": "desktop",
      "platform": "github",
      "stars": 0,
      "swedishProgress": 81,
      "quality": 7,
      "lastUpdate": "2026-03-20T20:42:28Z",
      "totalStrings": 306,
      "translatedStrings": 247,
      "url": "https://github.com/ZhongjiaoGPT-Platform/ZhongjiaoGPT",
      "langCode": "sv"
    },
    {
      "name": "silver-octo-waffle",
      "category": "desktop",
      "platform": "github",
      "stars": 0,
      "swedishProgress": 81,
      "quality": 7,
      "lastUpdate": "2026-03-20T20:42:30Z",
      "totalStrings": 431,
      "translatedStrings": 349,
      "url": "https://github.com/okerekechinweotito/silver-octo-waffle",
      "langCode": "sv"
    },
    {
      "name": "Validator",
      "category": "desktop",
      "platform": "github",
      "stars": 0,
      "swedishProgress": 81,
      "quality": 7,
      "lastUpdate": "2026-03-20T20:42:30Z",
      "totalStrings": 806,
      "translatedStrings": 652,
      "url": "https://github.com/Universal-Omega/Validator",
      "langCode": "sv"
    },
    {
      "name": "Node.js",
      "category": "development",
      "platform": "crowdin",
      "stars": 95000,
      "swedishProgress": 80,
      "quality": 8,
      "lastUpdate": "2026-03-20T20:42:20Z",
      "totalStrings": 1500,
      "translatedStrings": 1200,
      "url": "https://github.com/search?q=Node.js language:Swedish",
      "langCode": "sv"
    },
    {
      "name": "gwenview",
      "category": "desktop",
      "platform": "kde",
      "stars": 0,
      "swedishProgress": 80,
      "quality": 8,
      "lastUpdate": "2026-03-20T20:42:20Z",
      "totalStrings": 560,
      "translatedStrings": 448,
      "url": "https://l10n.kde.org/stats/gui/trunk-kf6/gwenview/sv/",
      "langCode": "sv"
    },
    {
      "name": "kdeconnect",
      "category": "desktop",
      "platform": "kde",
      "stars": 0,
      "swedishProgress": 80,
      "quality": 8,
      "lastUpdate": "2026-03-20T20:42:20Z",
      "totalStrings": 1180,
      "translatedStrings": 944,
      "url": "https://l10n.kde.org/stats/gui/trunk-kf6/kdeconnect/sv/",
      "langCode": "sv"
    },
    {
      "name": "kwin",
      "category": "desktop",
      "platform": "kde",
      "stars": 0,
      "swedishProgress": 80,
      "quality": 8,
      "lastUpdate": "2026-03-20T20:42:20Z",
      "totalStrings": 1220,
      "translatedStrings": 976,
      "url": "https://l10n.kde.org/stats/gui/trunk-kf6/kwin/sv/",
      "langCode": "sv"
    },
    {
      "name": "plasma-workspace",
      "category": "desktop",
      "platform": "kde",
      "stars": 0,
      "swedishProgress": 80,
      "quality": 8,
      "lastUpdate": "2026-03-20T20:42:20Z",
      "totalStrings": 640,
      "translatedStrings": 512,
      "url": "https://l10n.kde.org/stats/gui/trunk-kf6/plasma-workspace/sv/",
      "langCode": "sv"
    },
    {
      "name": "StreamlineEDU",
      "category": "system",
      "platform": "github",
      "stars": 0,
      "swedishProgress": 80,
      "quality": 7,
      "lastUpdate": "2026-03-20T20:42:23Z",
      "totalStrings": 555,
      "translatedStrings": 444,
      "url": "https://github.com/harxh-v/StreamlineEDU",
      "langCode": "sv"
    },
    {
      "name": "bookly-responsive-appointment-booking-tool",
      "category": "web",
      "platform": "github",
      "stars": 0,
      "swedishProgress": 80,
      "quality": 7,
      "lastUpdate": "2026-03-20T20:42:23Z",
      "totalStrings": 855,
      "translatedStrings": 684,
      "url": "https://github.com/WPPlugins/bookly-responsive-appointment-booking-tool",
      "langCode": "sv"
    },
    {
      "name": "mediawiki-extensions-PhabricatorLogin",
      "category": "media",
      "platform": "github",
      "stars": 0,
      "swedishProgress": 80,
      "quality": 7,
      "lastUpdate": "2026-03-20T20:42:30Z",
      "totalStrings": 580,
      "translatedStrings": 464,
      "url": "https://github.com/yangboz/mediawiki-extensions-PhabricatorLogin",
      "langCode": "sv"
    },
    {
      "name": "OpenCPN",
      "category": "desktop",
      "platform": "github",
      "stars": 0,
      "swedishProgress": 79,
      "quality": 7,
      "lastUpdate": "2026-03-20T20:42:23Z",
      "totalStrings": 329,
      "translatedStrings": 259,
      "url": "https://github.com/bdbcat/OpenCPN",
      "langCode": "sv"
    },
    {
      "name": "ilovepdf-wp",
      "category": "desktop",
      "platform": "github",
      "stars": 0,
      "swedishProgress": 79,
      "quality": 7,
      "lastUpdate": "2026-03-20T20:42:23Z",
      "totalStrings": 654,
      "translatedStrings": 516,
      "url": "https://github.com/ilovepdf/ilovepdf-wp",
      "langCode": "sv"
    },
    {
      "name": "RSV-Challenge",
      "category": "desktop",
      "platform": "github",
      "stars": 0,
      "swedishProgress": 79,
      "quality": 7,
      "lastUpdate": "2026-03-20T20:42:25Z",
      "totalStrings": 654,
      "translatedStrings": 516,
      "url": "https://github.com/Stenway/RSV-Challenge",
      "langCode": "sv"
    },
    {
      "name": "git_test",
      "category": "development",
      "platform": "github",
      "stars": 0,
      "swedishProgress": 79,
      "quality": 7,
      "lastUpdate": "2026-03-20T20:42:25Z",
      "totalStrings": 454,
      "translatedStrings": 358,
      "url": "https://github.com/williamastrom/git_test",
      "langCode": "sv"
    },
    {
      "name": "references",
      "category": "desktop",
      "platform": "github",
      "stars": 0,
      "swedishProgress": 79,
      "quality": 7,
      "lastUpdate": "2026-03-20T20:42:30Z",
      "totalStrings": 879,
      "translatedStrings": 694,
      "url": "https://github.com/OpenNumismat/references",
      "langCode": "sv"
    },
    {
      "name": "OnlyOffice",
      "category": "desktop",
      "platform": "github",
      "stars": 4000,
      "swedishProgress": 78,
      "quality": 8,
      "lastUpdate": "2026-03-20T20:42:20Z",
      "totalStrings": 8000,
      "translatedStrings": 6240,
      "url": "https://github.com/search?q=OnlyOffice language:Swedish",
      "langCode": "sv"
    },
    {
      "name": "DateTime-Locale",
      "category": "desktop",
      "platform": "github",
      "stars": 0,
      "swedishProgress": 78,
      "quality": 7,
      "lastUpdate": "2026-03-20T20:42:23Z",
      "totalStrings": 328,
      "translatedStrings": 255,
      "url": "https://github.com/houseabsolute/DateTime-Locale",
      "langCode": "sv"
    },
    {
      "name": "events-manager-wordpress",
      "category": "desktop",
      "platform": "github",
      "stars": 0,
      "swedishProgress": 78,
      "quality": 7,
      "lastUpdate": "2026-03-20T20:42:23Z",
      "totalStrings": 953,
      "translatedStrings": 743,
      "url": "https://github.com/bippo/events-manager-wordpress",
      "langCode": "sv"
    },
    {
      "name": "color-fns",
      "category": "web",
      "platform": "github",
      "stars": 0,
      "swedishProgress": 78,
      "quality": 7,
      "lastUpdate": "2026-03-20T20:42:25Z",
      "totalStrings": 803,
      "translatedStrings": 626,
      "url": "https://github.com/baianat/color-fns",
      "langCode": "sv"
    },
    {
      "name": "mediawiki-extensions-GPGMail",
      "category": "web",
      "platform": "github",
      "stars": 0,
      "swedishProgress": 78,
      "quality": 7,
      "lastUpdate": "2026-03-20T20:42:30Z",
      "totalStrings": 728,
      "translatedStrings": 567,
      "url": "https://github.com/wikimedia/mediawiki-extensions-GPGMail",
      "langCode": "sv"
    },
    {
      "name": "minigalaxy",
      "category": "desktop",
      "platform": "github",
      "stars": 0,
      "swedishProgress": 77,
      "quality": 7,
      "lastUpdate": "2026-03-20T20:42:23Z",
      "totalStrings": 502,
      "translatedStrings": 386,
      "url": "https://github.com/sharkwouter/minigalaxy",
      "langCode": "sv"
    },
    {
      "name": "qterest",
      "category": "desktop",
      "platform": "github",
      "stars": 0,
      "swedishProgress": 77,
      "quality": 7,
      "lastUpdate": "2026-03-20T20:42:23Z",
      "totalStrings": 727,
      "translatedStrings": 559,
      "url": "https://github.com/qteab/qterest",
      "langCode": "sv"
    },
    {
      "name": "vue-tailwind",
      "category": "web",
      "platform": "github",
      "stars": 0,
      "swedishProgress": 77,
      "quality": 7,
      "lastUpdate": "2026-03-20T20:42:25Z",
      "totalStrings": 252,
      "translatedStrings": 194,
      "url": "https://github.com/alfonsobries/vue-tailwind",
      "langCode": "sv"
    },
    {
      "name": "spreadsheet-sql",
      "category": "desktop",
      "platform": "github",
      "stars": 0,
      "swedishProgress": 77,
      "quality": 7,
      "lastUpdate": "2026-03-20T20:42:25Z",
      "totalStrings": 402,
      "translatedStrings": 309,
      "url": "https://github.com/jupemara/spreadsheet-sql",
      "langCode": "sv"
    },
    {
      "name": "papi",
      "category": "development",
      "platform": "github",
      "stars": 0,
      "swedishProgress": 76,
      "quality": 7,
      "lastUpdate": "2026-03-20T20:42:23Z",
      "totalStrings": 226,
      "translatedStrings": 171,
      "url": "https://github.com/wp-papi/papi",
      "langCode": "sv"
    },
    {
      "name": "ecclesiacrm",
      "category": "desktop",
      "platform": "github",
      "stars": 0,
      "swedishProgress": 76,
      "quality": 7,
      "lastUpdate": "2026-03-20T20:42:28Z",
      "totalStrings": 476,
      "translatedStrings": 361,
      "url": "https://github.com/phili67/ecclesiacrm",
      "langCode": "sv"
    },
    {
      "name": "systemd",
      "category": "system",
      "platform": "github",
      "stars": 12000,
      "swedishProgress": 75,
      "quality": 8,
      "lastUpdate": "2026-03-20T20:42:20Z",
      "totalStrings": 1200,
      "translatedStrings": 900,
      "url": "https://github.com/search?q=systemd language:Swedish",
      "langCode": "sv"
    },
    {
      "name": "tabler-icons-tsx",
      "category": "desktop",
      "platform": "github",
      "stars": 0,
      "swedishProgress": 75,
      "quality": 7,
      "lastUpdate": "2026-03-20T20:42:25Z",
      "totalStrings": 700,
      "translatedStrings": 525,
      "url": "https://github.com/hashrock/tabler-icons-tsx",
      "langCode": "sv"
    },
    {
      "name": "EvolvingSketch",
      "category": "development",
      "platform": "github",
      "stars": 0,
      "swedishProgress": 75,
      "quality": 7,
      "lastUpdate": "2026-03-20T20:42:25Z",
      "totalStrings": 875,
      "translatedStrings": 656,
      "url": "https://github.com/Snowflyt/EvolvingSketch",
      "langCode": "sv"
    },
    {
      "name": "SetupVPN",
      "category": "web",
      "platform": "github",
      "stars": 0,
      "swedishProgress": 75,
      "quality": 7,
      "lastUpdate": "2026-03-20T20:42:28Z",
      "totalStrings": 350,
      "translatedStrings": 262,
      "url": "https://github.com/qin-ziqi/SetupVPN",
      "langCode": "sv"
    },
    {
      "name": "immich",
      "category": "development",
      "platform": "github",
      "stars": 0,
      "swedishProgress": 75,
      "quality": 7,
      "lastUpdate": "2026-03-20T20:42:30Z",
      "totalStrings": 650,
      "translatedStrings": 487,
      "url": "https://github.com/immich-app/immich",
      "langCode": "sv"
    },
    {
      "name": "OpenSSL",
      "category": "security",
      "platform": "github",
      "stars": 24000,
      "swedishProgress": 70,
      "quality": 8,
      "lastUpdate": "2026-03-20T20:42:20Z",
      "totalStrings": 1000,
      "translatedStrings": 700,
      "url": "https://github.com/search?q=OpenSSL language:Swedish",
      "langCode": "sv"
    }
  ],
  "lastUpdated": "2026-03-20T20:42:32.884774+00:00",
  "totalProjects": 155,
  "sources": [
    "major",
    "gnome",
    "kde",
    "github",
    "pontoon"
  ]
};

// L10n Overview Data Module
class L10nData {
    constructor() {
        this.projects = REAL_DATA.projects;
        this.stats = {};
        this.lastUpdate = new Date(REAL_DATA.lastUpdated);
        this.init();
    }

    async init() {
        // Use real data instead of mock
        this.updateStats();
    }

    async loadData() {
        // Data is already loaded from REAL_DATA
        this.projects = REAL_DATA.projects;
        this.lastUpdate = new Date(REAL_DATA.lastUpdated);
    }

    updateStats() {
        const totalProjects = this.projects.length;
        const swedishProjects = this.projects.filter(p => p.swedishProgress > 0).length;
        const completeProjects = this.projects.filter(p => p.swedishProgress >= 90).length;
        
        // Updated today
        const today = new Date();
        const updatedToday = this.projects.filter(p => {
            const lastUpdate = new Date(p.lastUpdate);
            const diff = today - lastUpdate;
            return diff < 24 * 60 * 60 * 1000;
        }).length;

        this.stats = {
            totalProjects,
            swedishProjects,
            completeProjects,
            updatedToday,
            averageProgress: Math.round(
                this.projects.reduce((sum, p) => sum + p.swedishProgress, 0) / totalProjects
            ),
            averageQuality: swedishProjects > 0 ? (
                this.projects
                    .filter(p => p.quality > 0)
                    .reduce((sum, p) => sum + p.quality, 0) / swedishProjects
            ).toFixed(1) : "0.0"
        };

        // Update hero stats
        const totalEl = document.getElementById('total-projects');
        const swedishEl = document.getElementById('swedish-projects');
        const completeEl = document.getElementById('complete-projects');
        const updatedEl = document.getElementById('updated-today');
        
        if (totalEl) totalEl.textContent = totalProjects.toLocaleString();
        if (swedishEl) swedishEl.textContent = swedishProjects.toLocaleString();
        if (completeEl) completeEl.textContent = completeProjects.toLocaleString();
        if (updatedEl) updatedEl.textContent = updatedToday.toLocaleString();
    }

    getProjects(filters = {}, sortBy = 'stars', sortOrder = 'desc', page = 1, pageSize = 50) {
        let filtered = [...this.projects];

        // Apply filters
        if (filters.search) {
            const searchTerm = filters.search.toLowerCase();
            filtered = filtered.filter(p => 
                p.name.toLowerCase().includes(searchTerm) ||
                p.category.toLowerCase().includes(searchTerm) ||
                p.platform.toLowerCase().includes(searchTerm) ||
                (p.description && p.description.toLowerCase().includes(searchTerm))
            );
        }

        if (filters.category) {
            filtered = filtered.filter(p => p.category === filters.category);
        }

        if (filters.platform) {
            filtered = filtered.filter(p => p.platform === filters.platform);
        }

        if (filters.status) {
            switch(filters.status) {
                case 'complete':
                    filtered = filtered.filter(p => p.swedishProgress >= 90);
                    break;
                case 'partial':
                    filtered = filtered.filter(p => p.swedishProgress >= 50 && p.swedishProgress < 90);
                    break;
                case 'minimal':
                    filtered = filtered.filter(p => p.swedishProgress >= 10 && p.swedishProgress < 50);
                    break;
                case 'none':
                    filtered = filtered.filter(p => p.swedishProgress > 0 && p.swedishProgress < 10);
                    break;
                case 'missing':
                    filtered = filtered.filter(p => p.swedishProgress === 0);
                    break;
            }
        }

        // Apply sorting
        filtered.sort((a, b) => {
            let aVal = a[sortBy];
            let bVal = b[sortBy];

            if (sortBy === 'lastUpdate') {
                aVal = new Date(aVal);
                bVal = new Date(bVal);
            }

            if (sortBy === 'name') {
                return sortOrder === 'asc' ? 
                    aVal.localeCompare(bVal) : bVal.localeCompare(aVal);
            }

            if (sortOrder === 'asc') {
                return aVal - bVal;
            } else {
                return bVal - aVal;
            }
        });

        // Apply pagination
        const total = filtered.length;
        const startIndex = (page - 1) * pageSize;
        const endIndex = startIndex + pageSize;
        const pageData = filtered.slice(startIndex, endIndex);

        return {
            projects: pageData,
            total: total,
            page: page,
            pageSize: pageSize,
            totalPages: Math.ceil(total / pageSize)
        };
    }

    getChartData() {
        const qualityDistribution = [0, 0, 0, 0]; // Poor, Good, Excellent, Missing
        const activityData = new Array(30).fill(0);
        const platformCounts = {};
        const categoryCounts = {};

        this.projects.forEach(project => {
            // Quality distribution
            if (project.quality === 0) {
                qualityDistribution[3]++; // Missing
            } else if (project.quality <= 6) {
                qualityDistribution[0]++; // Poor
            } else if (project.quality <= 8) {
                qualityDistribution[1]++; // Good
            } else {
                qualityDistribution[2]++; // Excellent
            }

            // Platform counts
            platformCounts[project.platform] = (platformCounts[project.platform] || 0) + 1;

            // Category counts (only projects with Swedish)
            if (project.swedishProgress > 0) {
                categoryCounts[project.category] = (categoryCounts[project.category] || 0) + 1;
            }

            // Activity data
            const lastUpdate = new Date(project.lastUpdate);
            const daysDiff = Math.floor((new Date() - lastUpdate) / (1000 * 60 * 60 * 24));
            if (daysDiff < 30) {
                activityData[29 - daysDiff]++;
            }
        });

        return {
            quality: {
                labels: ['Låg kvalitet', 'Bra kvalitet', 'Utmärkt kvalitet', 'Saknar svenska'],
                data: qualityDistribution,
                colors: ['#ef4444', '#f97316', '#22c55e', '#6b7280']
            },
            activity: {
                labels: Array.from({length: 30}, (_, i) => {
                    const date = new Date();
                    date.setDate(date.getDate() - (29 - i));
                    return date.toISOString().split('T')[0];
                }),
                data: activityData
            },
            platforms: {
                labels: Object.keys(platformCounts),
                data: Object.values(platformCounts),
                colors: ['#10b981', '#2563eb', '#f59e0b', '#1f2937', '#8b5cf6', '#ef4444', '#6b7280']
            },
            categories: {
                labels: Object.keys(categoryCounts),
                data: Object.values(categoryCounts)
            }
        };
    }

    async refreshData() {
        // In a real implementation, this would fetch fresh data
        // For now, we use the static REAL_DATA
        this.updateStats();
        
        // Trigger refresh event
        document.dispatchEvent(new CustomEvent('dataRefresh'));
    }
}

// Create global instance
const l10nData = new L10nData();
